### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by SylviaAKK** [HenryGentry/weibosignin#3]
登录并获取签到列表后开始签到第一个超话时发生问题
准备签到超级话题->（这里是正常显示的超话名字）
Traceback (most recent call last):
  File "weibosign.py", line 196, in <module>
    signin(tempCookie, item)
  File "weibosign.py", line 124, in signin
    respJson = response.json()
  File "E:\Python\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "E:\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 3 (char 3)

看了半天没有找到json编码的问题，求教怎么解决，谢谢

**Comment by HenryGentry** [comment]
这个报错应该是接口响应报错了  可以在124行把response打印出来看是返回了什么 再进行定位（该问题我今晚也遇到了 后面看下怎么解决

**Comment by SylviaAKK** [comment]
response = session.get(url, headers=headers, params=data)
    print(response)
    respJson = response.json()
    print(respJson)

是直接加print嘛，好像不能打印出来？还是一模一样的报错诶

**Comment by Xiaobin2333** [comment]
通过print发现程序输出的并不是json格式文本，通过浏览器访问签到url能正常签到，返回格式也是json，随后抓包对比过请求参数也没有问题，这个问题困扰了很久。但是后来仔细查看发现抓包的cookies与程序获取到的cookies不同，程序使用的是手机cookies。经过测试发现手机cookies能正常获取到超话列表，电脑cookies则无法获取，使用电脑cookies能正常签到，手机cookies则返回了一个带有重定向的html文件。通过html文件发现微博通过重定向在签到url增加了两个参数（display=0&retcode=6102），增加这两个参数后，再次请求发现返回格式变回了json，但是返回code为382001参数错误。所以基本把问题锁定在了cookies上，可能微博更新了，手机cookies与电脑cookies不通用。

**Comment by zzhhxx** [comment]
他好像增加了判断是否为移动端，把后面两个参数删除后返回有如下：
<script language=javascript type="text/javascript">function ismobile() {
      if (/(ipad|Tablet|OperaMini|SmartPhone|iPhone|iPod|Symbian|WindowsCE|Mobile|MOT|MUAI|Motorola|Nokia|SonyEricsson|Android)/i.test(navigator.userAgent)) {
        return true;
      }
      return false;
    }

    if (ismobile()) {
      url = 'https://passport.sinaimg.cn/html/sso/forbiddenh5.html';
    } else {
      url = 'https://passport.sinaimg.cn/html/sso/forbiddenpc.html';
    }
    window.location.href = url;</script>

**Comment by zzhhxx** [comment]
这个有办法解决吗，在获取电脑端cookies后再访问m.weibo.cn然后用这个cookies能返回json，但是返回代码为382001

**Comment by Xiaobin2333** [comment]
> 这个有办法解决吗，在获取电脑端cookies后再访问m.weibo.cn然后用这个cookies能返回json，但是返回代码为382001

你需要获取的是weibo.com的cookies，此cookies24小时会过期，需要重新获取。

**Comment by zzhhxx** [comment]
> > 这个有办法解决吗，在获取电脑端cookies后再访问m.weibo.cn然后用这个cookies能返回json，但是返回代码为382001
> 
> 你需要获取的是weibo.com的cookies，此cookies24小时会过期，需要重新获取。

我试一下
